[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Ripserer = "aa79e827-bd0b-42a8-9f10-2b302677a641"
